"""
Swarm Mission Planner  (pymavlink only — no dronekit)
======================================================
Executes multi-drone coverage missions generated by main_2_.py.

Pipeline:
  1. Runs main_2_.py  →  produces missions/drone_N.waypoints
  2. Connects to each drone through MAVProxy's UDP --out port
  3. Arms, takes off (staggered by DRONE_DELAY), uploads & executes mission
  4. Obstacle-avoidance hold during transit phase only
  5. Lands via SET_MODE → LAND  (not RTL)

SITL setup (run each block in its own terminal BEFORE this script):
  # Drone 1
  sim_vehicle.py -v ArduCopter -I0 --sysid 1
  mavproxy.py --retries 5 --master tcp:127.0.0.1:5760 --sitl 127.0.0.1:5501 \
              --out 127.0.0.1:14550 --map --console

  # Drone 2
  sim_vehicle.py -v ArduCopter -I1 --sysid 2
  mavproxy.py --retries 5 --master tcp:127.0.0.1:5770 --sitl 127.0.0.1:5511 \
              --out 127.0.0.1:14560 --map --console

  # Then:
  python swarm_mission_planner.py

MAVProxy uses --out without 'udp:' prefix; it pushes UDP packets TO that
address.  pymavlink must therefore LISTEN (server side) using 'udpin:'.

Real hardware: replace conn_str with e.g. '/dev/ttyUSB0,57600'
"""

import argparse
import os
import sys
import time
import math
import threading
import subprocess
import glob
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

from pymavlink import mavutil

# ═══════════════════════════════════════════════════════════════════════════
#  USER CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════

MAIN_SCRIPT  = 'main_new.py'
MISSIONS_DIR = 'missions'

# Must match main_2_.py DRONE_DELAY
DRONE_DELAY  = 60.0    # seconds between consecutive takeoffs

# Must match main_2_.py ALTITUDE
TAKEOFF_ALT  = 6.0     # metres (relative / AGL)

# ── Collision avoidance (transit phase only) ─────────────────────────────
MIN_HORIZ_DIST   = 1.0   # metres — trigger hold if closer than this
MIN_ALT_DIFF     = 1.0   # metres — altitude gap that waives the horiz check
AVOIDANCE_HOLD_S = 2.0   # seconds between re-checks while holding

# ── Timeouts ─────────────────────────────────────────────────────────────
CONNECT_TIMEOUT  = 30    # seconds — wait for first heartbeat
ARM_TIMEOUT      = 30    # seconds
TAKEOFF_TIMEOUT  = 40    # seconds — time to reach TAKEOFF_ALT
MISSION_TIMEOUT  = 900   # seconds — max time from AUTO start to landing
LAND_TIMEOUT     = 60    # seconds — time to confirm landed

# ── Poll rate ────────────────────────────────────────────────────────────
POLL_HZ = 4              # position update rate (times/second)

# ── Per-drone connection config ───────────────────────────────────────────
# conn_str for SITL via MAVProxy --out:
#   MAVProxy writes  "--out 127.0.0.1:14550"   (no prefix, sends UDP)
#   pymavlink reads  "udpin:127.0.0.1:14550"   (listen on that port)
#
# conn_str for real hardware:
#   '/dev/ttyUSB0,57600'   or   'udpout:192.168.1.10:14550'
#
# sysid must match ArduPilot SYSID_THISMAV parameter.
DRONES: List[Tuple[int, str, int]] = [
    # (1-based index,  conn_str,                     sysid)
    (1,  'udpin:127.0.0.1:14550',  1),
    (2,  'udpin:127.0.0.1:14560',  2),
    # add more rows here …
]

# ═══════════════════════════════════════════════════════════════════════════
#  LOGGING
# ═══════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(message)s',
    datefmt='%H:%M:%S',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('swarm_mission.log', mode='w'),
    ],
)
log = logging.getLogger('swarm')


# ═══════════════════════════════════════════════════════════════════════════
#  SHARED DRONE STATE
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class DroneState:
    index:           int
    sysid:           int
    conn_str:        str
    mission_wps:     list                         = field(default_factory=list)
    lawnmower_start: Optional[Tuple[float,float]] = None   # (lat, lon)

    # Live telemetry — written by owner thread, read by sibling threads
    lat:        float = 0.0
    lon:        float = 0.0
    alt_rel:    float = 0.0
    in_transit: bool  = True   # False after drone reaches lawnmower start WP
    done:       bool  = False
    error:      Optional[str] = None
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def set_pos(self, lat: float, lon: float, alt: float):
        with self._lock:
            self.lat, self.lon, self.alt_rel = lat, lon, alt

    def get_pos(self) -> Tuple[float, float, float]:
        with self._lock:
            return self.lat, self.lon, self.alt_rel


# ═══════════════════════════════════════════════════════════════════════════
#  COORDINATE HELPERS
# ═══════════════════════════════════════════════════════════════════════════

R_EARTH = 6_371_000.0

def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in metres."""
    p1, p2 = math.radians(lat1), math.radians(lat2)
    a = (math.sin(math.radians(lat2 - lat1) / 2) ** 2
         + math.cos(p1) * math.cos(p2)
         * math.sin(math.radians(lon2 - lon1) / 2) ** 2)
    return 2 * R_EARTH * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ═══════════════════════════════════════════════════════════════════════════
#  WAYPOINT FILE PARSER
# ═══════════════════════════════════════════════════════════════════════════

def parse_waypoint_file(filepath: str) -> List[Tuple[float, float, float]]:
    """Parse QGC WPL 110 file → list of (lat, lon, alt_rel), home excluded."""
    wps = []
    try:
        with open(filepath) as f:
            lines = f.readlines()
        for line in lines[1:]:          # skip header row
            parts = line.strip().split('\t')
            if len(parts) < 11:
                continue
            seq = int(parts[0])
            cmd = int(parts[3])
            lat = float(parts[8])
            lon = float(parts[9])
            alt = float(parts[10])
            if seq == 0:
                continue               # skip home WP
            if cmd == 16:              # MAV_CMD_NAV_WAYPOINT
                wps.append((lat, lon, alt))
    except Exception as exc:
        log.error(f"parse_waypoint_file({filepath}): {exc}")
    return wps


# ═══════════════════════════════════════════════════════════════════════════
#  LOW-LEVEL MAVLink HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def wait_heartbeat(mav, timeout: float = CONNECT_TIMEOUT):
    """Block until the first HEARTBEAT arrives from the autopilot."""
    log.info("    Waiting for HEARTBEAT …")
    msg = mav.wait_heartbeat(timeout=timeout)
    if msg is None:
        raise TimeoutError("No HEARTBEAT received within timeout")
    log.info(f"    HEARTBEAT ✓  sysid={mav.target_system}  "
             f"compid={mav.target_component}")


def request_streams(mav, hz: int = POLL_HZ):
    """Ask autopilot to stream position + status messages."""
    for stream_id in (
        mavutil.mavlink.MAV_DATA_STREAM_POSITION,
        mavutil.mavlink.MAV_DATA_STREAM_EXTENDED_STATUS,
        mavutil.mavlink.MAV_DATA_STREAM_EXTRA1,
    ):
        mav.mav.request_data_stream_send(
            mav.target_system, mav.target_component,
            stream_id, hz, 1,
        )


def get_gps(mav, timeout: float = 2.0) -> Optional[Tuple[float, float, float]]:
    """Return (lat_deg, lon_deg, alt_rel_m) or None."""
    msg = mav.recv_match(type='GLOBAL_POSITION_INT',
                         blocking=True, timeout=timeout)
    if msg is None:
        return None
    return msg.lat / 1e7, msg.lon / 1e7, msg.relative_alt / 1000.0


def set_mode(mav, mode_name: str, timeout: float = 5.0):
    """Set flight mode by name and wait for HEARTBEAT confirmation."""
    mapping = mav.mode_mapping()
    if mode_name not in mapping:
        raise ValueError(f"Unknown mode '{mode_name}'. "
                         f"Available: {list(mapping)}")
    mode_id = mapping[mode_name]
    mav.mav.set_mode_send(
        mav.target_system,
        mavutil.mavlink.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
        mode_id,
    )
    t0 = time.time()
    while time.time() - t0 < timeout:
        hb = mav.recv_match(type='HEARTBEAT', blocking=True, timeout=1)
        if hb and hb.custom_mode == mode_id:
            return
    log.warning(f"    set_mode({mode_name}) — no confirmation within {timeout}s")


def send_command_long(mav, command: int,
                      p1=0.0, p2=0.0, p3=0.0,
                      p4=0.0, p5=0.0, p6=0.0, p7=0.0,
                      confirmation: int = 0):
    mav.mav.command_long_send(
        mav.target_system, mav.target_component,
        command, confirmation,
        p1, p2, p3, p4, p5, p6, p7,
    )


def is_armed(mav, timeout: float = 2.0) -> bool:
    hb = mav.recv_match(type='HEARTBEAT', blocking=True, timeout=timeout)
    if hb is None:
        return False
    return bool(hb.base_mode & mavutil.mavlink.MAV_MODE_FLAG_SAFETY_ARMED)


# ═══════════════════════════════════════════════════════════════════════════
#  MISSION UPLOAD  (MISSION_ITEM_INT handshake)
# ═══════════════════════════════════════════════════════════════════════════

def upload_mission(mav, wps: List[Tuple[float, float, float]], tag: str):
    """
    Upload waypoint list using the MAVLink mission upload handshake.
    Item 0 = dummy home (current position); items 1..N = coverage WPs.
    """
    total = len(wps) + 1   # +1 for the home item at seq=0

    # Send MISSION_COUNT to start the handshake
    mav.mav.mission_count_send(
        mav.target_system, mav.target_component,
        total,
        mavutil.mavlink.MAV_MISSION_TYPE_MISSION,
    )

    sent = 0
    t0   = time.time()
    while sent < total:
        if time.time() - t0 > 30:
            raise TimeoutError(f"{tag} Upload timed out at item {sent}/{total}")

        # Accept both MISSION_REQUEST_INT and legacy MISSION_REQUEST
        req = mav.recv_match(type=['MISSION_REQUEST_INT', 'MISSION_REQUEST'],
                             blocking=True, timeout=3)
        if req is None:
            continue

        seq = req.seq

        if seq == 0:
            # Home item — use vehicle's current position
            pos = get_gps(mav, timeout=3) or (0.0, 0.0, 0.0)
            lat_i = int(pos[0] * 1e7)
            lon_i = int(pos[1] * 1e7)
            alt_f = 0.0
            autocont = 0
        else:
            wp_lat, wp_lon, wp_alt = wps[seq - 1]
            lat_i = int(wp_lat * 1e7)
            lon_i = int(wp_lon * 1e7)
            alt_f = float(wp_alt)
            autocont = 1

        mav.mav.mission_item_int_send(
            mav.target_system, mav.target_component,
            seq,
            mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,
            mavutil.mavlink.MAV_CMD_NAV_WAYPOINT,
            0,          # current
            autocont,
            0, 0, 0, 0, # param1-4
            lat_i, lon_i, alt_f,
            mavutil.mavlink.MAV_MISSION_TYPE_MISSION,
        )
        sent = seq + 1

    # Wait for MISSION_ACK
    ack = mav.recv_match(type='MISSION_ACK', blocking=True, timeout=5)
    if ack is None or ack.type != mavutil.mavlink.MAV_MISSION_ACCEPTED:
        raise RuntimeError(f"{tag} MISSION_ACK not accepted: {ack}")
    log.info(f"{tag} Mission uploaded ✓  ({len(wps)} WPs)")


# ═══════════════════════════════════════════════════════════════════════════
#  COLLISION AVOIDANCE
# ═══════════════════════════════════════════════════════════════════════════

def collision_warning(states: List[DroneState], my_idx: int) -> Optional[str]:
    """
    Returns a description if drone my_idx risks collision with any other drone
    that is still in transit (before reaching its lawnmower start point).
    The horizontal check is waived when altitude separation >= MIN_ALT_DIFF.
    Returns None if airspace is clear.
    """
    me = states[my_idx]
    my_lat, my_lon, my_alt = me.get_pos()

    for i, other in enumerate(states):
        if i == my_idx or not other.in_transit:
            continue
        o_lat, o_lon, o_alt = other.get_pos()
        if abs(my_alt - o_alt) >= MIN_ALT_DIFF:
            continue    # sufficient vertical separation
        d = haversine(my_lat, my_lon, o_lat, o_lon)
        if d < MIN_HORIZ_DIST:
            return (f"D{me.index}↔D{other.index}  horiz={d:.2f}m  "
                    f"Δalt={abs(my_alt - o_alt):.2f}m")
    return None


def hold_position(mav, lat: float, lon: float, alt: float):
    """Command vehicle to hold its current position (GUIDED + position target)."""
    mav.mav.set_position_target_global_int_send(
        0,
        mav.target_system, mav.target_component,
        mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,
        0b0000111111111000,   # type_mask: only lat/lon/alt used
        int(lat * 1e7), int(lon * 1e7), alt,
        0, 0, 0,              # vx, vy, vz (ignored)
        0, 0, 0,              # ax, ay, az (ignored)
        0, 0,                 # yaw, yaw_rate (ignored)
    )


# ═══════════════════════════════════════════════════════════════════════════
#  PER-DRONE THREAD
# ═══════════════════════════════════════════════════════════════════════════

def drone_thread(state: DroneState, all_states: List[DroneState],
                 skip_prearm: bool = False):
    tag = f"[D{state.index}|sys={state.sysid}]"

    # ── 1. Connect ───────────────────────────────────────────────────────────
    try:
        log.info(f"{tag} Connecting → {state.conn_str}")
        mav = mavutil.mavlink_connection(
            state.conn_str,
            source_system=255,       # GCS sysid (must differ from all drones)
            source_component=0,
            dialect='ardupilotmega',
        )
        wait_heartbeat(mav)
        # Lock onto this drone's sysid so messages to other drones are ignored
        mav.target_system    = state.sysid
        mav.target_component = mavutil.mavlink.MAV_COMP_ID_AUTOPILOT1
        request_streams(mav)
        log.info(f"{tag} Connected ✓")
    except Exception as exc:
        state.error = f"Connection failed: {exc}"
        log.error(f"{tag} {state.error}")
        return

    # ── 2. Validate mission ──────────────────────────────────────────────────
    wps = state.mission_wps
    if not wps:
        state.error = "Mission waypoint list is empty"
        log.error(f"{tag} {state.error}")
        return
    # First waypoint in the list is where the lawnmower pattern starts
    state.lawnmower_start = (wps[0][0], wps[0][1])

    # ── 3. Upload mission ────────────────────────────────────────────────────
    try:
        upload_mission(mav, wps, tag)
    except Exception as exc:
        state.error = f"Upload failed: {exc}"
        log.error(f"{tag} {state.error}")
        return

    # ── 4. Staggered takeoff delay ───────────────────────────────────────────
    delay = (state.index - 1) * DRONE_DELAY
    if delay > 0:
        log.info(f"{tag} Waiting {delay:.0f}s (staggered takeoff) …")
        time.sleep(delay)

    # ── 5. Wait for pre-arm checks (skippable via --skip-prearm) ────────────
    if skip_prearm:
        log.warning(f"{tag} Pre-arm checks SKIPPED (--skip-prearm)")
    else:
        log.info(f"{tag} Waiting for pre-arm checks …")
        t0 = time.time()
        while True:
            msg = mav.recv_match(type='SYS_STATUS', blocking=True, timeout=2)
            if msg is not None:
                present = msg.onboard_control_sensors_present
                healthy = msg.onboard_control_sensors_health
                if (present & healthy) == present:
                    log.info(f"{tag} Pre-arm checks passed ✓")
                    break
            if time.time() - t0 > ARM_TIMEOUT:
                state.error = "Pre-arm checks never passed"
                log.error(f"{tag} {state.error}")
                return
            time.sleep(1)

    # ── 6. GUIDED mode + arm ─────────────────────────────────────────────────
    set_mode(mav, 'GUIDED')
    time.sleep(0.5)

    log.info(f"{tag} Arming …")
    # p2=21196 bypasses pre-arm safety checks when skip_prearm is set
    send_command_long(mav, mavutil.mavlink.MAV_CMD_COMPONENT_ARM_DISARM,
                      p1=1, p2=21196 if skip_prearm else 0)

    t0 = time.time()
    while True:
        if is_armed(mav):
            log.info(f"{tag} Armed ✓")
            break
        if time.time() - t0 > ARM_TIMEOUT:
            state.error = "Arming timed out"
            log.error(f"{tag} {state.error}")
            return
        time.sleep(0.5)

    # ── 7. Takeoff ───────────────────────────────────────────────────────────
    log.info(f"{tag} Taking off to {TAKEOFF_ALT}m …")
    send_command_long(
        mav, mavutil.mavlink.MAV_CMD_NAV_TAKEOFF,
        p7=TAKEOFF_ALT,
    )

    t0 = time.time()
    while True:
        pos = get_gps(mav, timeout=2)
        if pos:
            state.set_pos(*pos)
            if pos[2] >= TAKEOFF_ALT * 0.92:
                log.info(f"{tag} Reached {pos[2]:.1f}m ✓")
                break
        if time.time() - t0 > TAKEOFF_TIMEOUT:
            state.error = "Takeoff timed out"
            log.error(f"{tag} {state.error}")
            return
        time.sleep(1.0 / POLL_HZ)

    # ── 8. Start mission (AUTO) ──────────────────────────────────────────────
    # Set current mission item to 1 (item 0 is the dummy home)
    mav.mav.mission_set_current_send(
        mav.target_system, mav.target_component, 1
    )
    time.sleep(0.3)
    set_mode(mav, 'AUTO')
    log.info(f"{tag} AUTO mission started")
    t_mission = time.time()

    # ── 9. Transit phase + collision avoidance ───────────────────────────────
    log.info(f"{tag} Transit phase: heading to lawnmower start …")
    while state.in_transit:
        pos = get_gps(mav, timeout=1)
        if pos:
            state.set_pos(*pos)
            cur_lat, cur_lon, cur_alt = pos

            # Check arrival at lawnmower start point (2 m acceptance radius)
            ls = state.lawnmower_start
            if ls and haversine(cur_lat, cur_lon, ls[0], ls[1]) < 2.0:
                state.in_transit = False
                log.info(f"{tag} Lawnmower start reached — transit done ✓")
                break

            # Collision check
            warn = collision_warning(all_states, state.index - 1)
            if warn:
                log.warning(f"{tag} COLLISION RISK: {warn} — holding position")
                set_mode(mav, 'GUIDED')
                hold_position(mav, cur_lat, cur_lon, cur_alt)
                # Spin until clear
                while True:
                    time.sleep(AVOIDANCE_HOLD_S)
                    pos2 = get_gps(mav, timeout=1)
                    if pos2:
                        state.set_pos(*pos2)
                        cur_lat, cur_lon, cur_alt = pos2
                    if not collision_warning(all_states, state.index - 1):
                        break
                    log.info(f"{tag} Still holding …")
                    hold_position(mav, cur_lat, cur_lon, cur_alt)
                log.info(f"{tag} Airspace clear — resuming AUTO")
                set_mode(mav, 'AUTO')

        if time.time() - t_mission > MISSION_TIMEOUT:
            state.error = "Transit phase timed out"
            log.error(f"{tag} {state.error}")
            return

        time.sleep(1.0 / POLL_HZ)

    # ── 10. Coverage phase: wait for mission complete ─────────────────────────
    log.info(f"{tag} Coverage phase — waiting for mission end …")
    last_wp = len(wps)   # WPs are 1-indexed on autopilot (item 0 = home)

    while True:
        pos = get_gps(mav, timeout=1)
        if pos:
            state.set_pos(*pos)

        # MISSION_ITEM_REACHED fires when each WP is hit
        reached = mav.recv_match(type='MISSION_ITEM_REACHED',
                                 blocking=False, timeout=0.2)
        if reached and reached.seq >= last_wp:
            log.info(f"{tag} Last waypoint reached ✓")
            break

        # Autopilot reverts to GUIDED after final WP in some configurations
        hb = mav.recv_match(type='HEARTBEAT', blocking=False, timeout=0.1)
        if hb:
            mode_rev = {v: k for k, v in mav.mode_mapping().items()}
            cur_mode = mode_rev.get(hb.custom_mode, '')
            if cur_mode in ('GUIDED', 'LOITER', 'BRAKE'):
                log.info(f"{tag} Autopilot → {cur_mode}; treating as mission done")
                break

        if time.time() - t_mission > MISSION_TIMEOUT:
            log.warning(f"{tag} Mission timeout — forcing land")
            break

        time.sleep(1.0 / POLL_HZ)

    state.done = True

    # ── 11. Land (mode LAND, not RTL) ────────────────────────────────────────
    log.info(f"{tag} Landing …")
    set_mode(mav, 'LAND')

    t0 = time.time()
    while True:
        pos = get_gps(mav, timeout=2)
        if pos:
            state.set_pos(*pos)
            if pos[2] < 0.3:
                log.info(f"{tag} Landed ✓  alt={pos[2]:.2f}m")
                break

        hb = mav.recv_match(type='HEARTBEAT', blocking=False, timeout=0.2)
        if hb and not (hb.base_mode & mavutil.mavlink.MAV_MODE_FLAG_SAFETY_ARMED):
            log.info(f"{tag} Disarmed — landed ✓")
            break

        if time.time() - t0 > LAND_TIMEOUT:
            log.warning(f"{tag} Land timeout — force-disarming")
            send_command_long(
                mav, mavutil.mavlink.MAV_CMD_COMPONENT_ARM_DISARM,
                p1=0, p2=21196,   # 21196 = force-disarm magic number
            )
            break

        time.sleep(1)

    mav.close()
    log.info(f"{tag} Done — connection closed")


# ═══════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════

def run_planner():
    log.info("═" * 62)
    log.info("STEP 1 — Generating missions (main_2_.py) …")
    log.info("═" * 62)
    try:
        subprocess.run([sys.executable, MAIN_SCRIPT], check=True)
        log.info("Mission planner finished ✓")
    except subprocess.CalledProcessError as exc:
        log.error(f"main_2_.py failed with exit code {exc.returncode}")
        sys.exit(1)
    except FileNotFoundError:
        log.error(f"Cannot find {MAIN_SCRIPT} — ensure it is in the same directory")
        sys.exit(1)


def load_missions() -> dict:
    pattern = os.path.join(MISSIONS_DIR, 'drone_*.waypoints')
    files   = sorted(glob.glob(pattern))
    if not files:
        log.error(f"No waypoint files found in {MISSIONS_DIR}/")
        sys.exit(1)
    missions = {}
    for fp in files:
        try:
            idx = int(os.path.basename(fp)
                      .replace('drone_', '').replace('.waypoints', ''))
        except ValueError:
            continue
        wps = parse_waypoint_file(fp)
        if not wps:
            log.warning(f"D{idx}: empty waypoint file — skipping")
            continue
        missions[idx] = wps
        log.info(f"  D{idx}: {len(wps)} waypoints  ← {fp}")
    return missions


def main():
    parser = argparse.ArgumentParser(description='Swarm Mission Planner')
    parser.add_argument(
        '--skip-prearm', action='store_true',
        help='Skip pre-arm sensor checks and force-arm each drone '
             '(useful for SITL or bench testing without full sensor suite)',
    )
    args = parser.parse_args()
    skip_prearm: bool = args.skip_prearm

    if skip_prearm:
        log.warning("⚠  --skip-prearm active: pre-arm checks will be bypassed")

    # Step 1 — generate missions
    run_planner()

    # Step 2 — load waypoint files
    log.info("═" * 62)
    log.info("STEP 2 — Loading waypoint files …")
    log.info("═" * 62)
    missions = load_missions()
    if not missions:
        log.error("No missions found — exiting")
        sys.exit(1)

    # Step 3 — build DroneState objects
    log.info("═" * 62)
    log.info("STEP 3 — Configuring swarm …")
    log.info("═" * 62)
    states: List[DroneState] = []
    for (idx, conn_str, sysid) in DRONES:
        if idx not in missions:
            log.warning(f"D{idx} has no mission file — skipping")
            continue
        s = DroneState(
            index       = idx,
            sysid       = sysid,
            conn_str    = conn_str,
            mission_wps = missions[idx],
        )
        states.append(s)
        log.info(f"  D{idx}  sysid={sysid}  {conn_str}  ({len(missions[idx])} WPs)")

    if not states:
        log.error("No drones configured — check DRONES list and mission files")
        sys.exit(1)

    # Step 4 — launch per-drone threads
    log.info("═" * 62)
    log.info(f"STEP 4 — Launching {len(states)} drone thread(s)  "
             f"DRONE_DELAY={DRONE_DELAY}s  ALT={TAKEOFF_ALT}m")
    log.info("═" * 62)

    threads = []
    for s in states:
        t = threading.Thread(
            target=drone_thread,
            args=(s, states, skip_prearm),
            name=f"D{s.index}",
            daemon=True,
        )
        threads.append(t)
        t.start()
        time.sleep(0.3)   # slight stagger so socket binds don't race

    for t in threads:
        t.join()

    # Summary
    log.info("═" * 62)
    log.info("SWARM COMPLETE")
    log.info("═" * 62)
    for s in states:
        if s.error:
            log.error(f"  D{s.index}  ✗  {s.error}")
        else:
            log.info(f"  D{s.index}  ✓  OK")


if __name__ == '__main__':
    main()